name: soft_plc_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.2.0
  soft_plc:
    path: ../soft_plc/

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0
